### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by fredzzt** [fython/BreadcrumbsView#1]
Caused by: java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to moe.feng.common.view.breadcrumbs.BreadcrumbsView$State
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at moe.feng.common.view.breadcrumbs.BreadcrumbsView.onRestoreInstanceState(BreadcrumbsView.java:210)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.View.dispatchRestoreInstanceState(View.java:17706)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3745)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.view.View.restoreHierarchyState(View.java:17684)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2131)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.app.Activity.onRestoreInstanceState(Activity.java:1103)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.app.Activity.performRestoreInstanceState(Activity.java:1058)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1260)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
12-04 17:30:09.092 10096 10096 E AndroidRuntime: 	... 9 more

**Comment by fython** [comment]
Fixed in 06a01208e0ebc4b2e54dfe3f2c426eac62c9976d . Now it can save/restore instance state normally.
