### ISSUE TITLE
Failed to resolve: moe.feng:BreadcrumbsView:latest-version

### ISSUE THREAD

**Issue by mridah** [fython/BreadcrumbsView#8]
Cannot add it in Gradle. It gives this error:

> Failed to resolve: moe.feng:BreadcrumbsView:latest-version

How to use it @fython ?

**Comment by fython** [comment]
Replace `latest-version` with the displayed version in ![](https://camo.githubusercontent.com/117f59a239d31c635800abfad05a24512bb1b574/68747470733a2f2f6a69747061636b2e696f2f762f6d6f652e66656e672f42726561646372756d6273566965772e737667) (`0.2.1`)
